[package]
name = "user_lib"
version = "0.0.1"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
output = { path = "../output" }
syscall = { path = "../syscall", features = ["user"] }
buddy_system_allocator = "0.6"

